export const userLoginConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
}

export const userRegisterConstants = {
    REGISTER_REQUEST:'REGISTER_REQUEST',
    REGISTER_FAILURE:'REGISTER_FAILURE',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',  
}

export const userUpdateConstants = {
    UPDATE_REQUEST:'UPDATE_REQUEST',
    UPDATE_FAILURE:'UPDATE_FAILURE',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',  
}

export const otpConstants = {
    OTP_REQUEST:'OTP_REQUEST',
    OTP_FAILURE:'OTP_FAILURE',
    OTP_SUCCESS:'OTP_SUCCESS',  
}

export const emailConstants = {
    EMAIL_REQUEST:'EMAIL_REQUEST',
    EMAIL_FAILURE:'EMAIL_FAILURE',
    EMAIL_SUCCESS:'EMAIL_SUCCESS',  
}

export const productConstants = {
    PRODUCT_REQUEST:'PRODUCT_REQUEST',
    PRODUCT_FAILURE:'PRODUCT_FAILURE',
    PRODUCT_SUCCESS:'PRODUCT_SUCCESS',    
}

export const newProductConstants = {
    NEW_PRODUCT_REQUEST:'NEW_PRODUCT_REQUEST',
    NEW_PRODUCT_FAILURE:'NEW_PRODUCT_FAILURE',
    NEW_PRODUCT_SUCCESS:'NEW_PRODUCT_SUCCESS',    
}

export const singleProductConstants = {
    SINGLE_PRODUCT_REQUEST:'SINGLE_PRODUCT_REQUEST',
    SINGLE_PRODUCT_FAILURE:'SINGLE_PRODUCT_FAILURE',
    SINGLE_PRODUCT_SUCCESS:'SINGLE_PRODUCT_SUCCESS',    
}

export const categoryConstants = {
    CATEGORY_REQUEST:'CATEGORY_REQUEST',
    CATEGORY_FAILURE:'CATEGORY_FAILURE',
    CATEGORY_SUCCESS:'CATEGORY_SUCCESS',    
}

export const searchConstants = {
    SEARCH_REQUEST:'SEARCH_REQUEST',
    SEARCH_FAILURE:'SEARCH_FAILURE',
    SEARCH_SUCCESS:'SEARCH_SUCCESS',    
}

export const filterConstants = {
    FILTER_REQUEST:'FILTER_REQUEST',
    FILTER_FAILURE:'FILTER_FAILURE',
    FILTER_SUCCESS:'FILTER_SUCCESS',    
}

export const relatedConstants = {
    RELATED_REQUEST:'RELATED_REQUEST',
    RELATED_FAILURE:'RELATED_FAILURE',
    RELATED_SUCCESS:'RELATED_SUCCESS',    
}

export const addToCartConstants = {
    ADDTOCART_REQUEST:'ADDTOCART_REQUEST',
    ADDTOCART_FAILURE:'ADDTOCART_FAILURE',
    ADDTOCART_SUCCESS:'ADDTOCART_SUCCESS',    
}

export const getCartDataConstants = {
    GETCARTDATA_REQUEST:'GETCARTDATA_REQUEST',
    GETCARTDATA_FAILURE:'GETCARTDATA_FAILURE',
    GETCARTDATA_SUCCESS:'GETCARTDATA_SUCCESS',    
}
export const removeCartDataConstants = {
    REMOVECARTDATA_REQUEST:'REMOVECARTDATA_REQUEST',
    REMOVECARTDATA_FAILURE:'REMOVECARTDATA_FAILURE',
    REMOVECARTDATA_SUCCESS:'REMOVECARTDATA_SUCCESS',    
}

export const removeSavedDataConstants = {
    REMOVE_SAVED_REQUEST:'REMOVE_SAVED_REQUEST',
    REMOVE_SAVED_FAILURE:'REMOVE_SAVED_FAILURE',
    REMOVE_SAVED_SUCCESS:'REMOVE_SAVED_SUCCESS',    
}

export const quantityEditConstants = {
    QUANTITY_EDIT_REQUEST:'QUANTITY_EDIT_REQUEST',
    QUANTITY_EDIT_FAILURE:'QUANTITY_EDIT_FAILURE',
    QUANTITY_EDIT_SUCCESS:'QUANTITY_EDIT_SUCCESS',    
}

export const orderConstants = {
    ORDER_REQUEST:'ORDER_REQUEST',
    ORDER_FAILURE:'ORDER_FAILURE',
    ORDER_SUCCESS:'ORDER_SUCCESS',    
}

export const paymentVerifyConstants = {
    PAYMENT_VERIFY_REQUEST:'PAYMENT_VERIFY_REQUEST',
    PAYMENT_VERIFY_FAILURE:'PAYMENT_VERIFY_FAILURE',
    PAYMENT_VERIFY_SUCCESS:'PAYMENT_VERIFY_SUCCESS',    
}

export const paymentConstants = {
    PAYMENT_REQUEST:'PAYMENT_REQUEST',
    PAYMENT_FAILURE:'PAYMENT_FAILURE',
    PAYMENT_SUCCESS:'PAYMENT_SUCCESS',    
}

export const trendingProductsConstants = {
    TRENDING_PRODUCTS_REQUEST:'TRENDING_PRODUCTS_REQUEST',
    TRENDING_PRODUCTS_FAILURE:'TRENDING_PRODUCTS_FAILURE',
    TRENDING_PRODUCTS_SUCCESS:'TRENDING_PRODUCTS_SUCCESS',    
}

export const saveConstants = {
    SAVE_REQUEST:'SAVE_REQUEST',
    SAVE_FAILURE:'SAVE_FAILURE',
    SAVE_SUCCESS:'SAVE_SUCCESS',    
}

export const getSavedConstants = {
    GET_SAVED_REQUEST:'GET_SAVED_REQUEST',
    GET_SAVED_FAILURE:'GET_SAVED_FAILURE',
    GET_SAVED_SUCCESS:'GET_SAVED_SUCCESS',    
}